-- AlterTable
ALTER TABLE "ContainerType" ALTER COLUMN "volume" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "carryingCapacity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "footprint" SET DATA TYPE DOUBLE PRECISION;
